[[file]]
name = "libcmumps_a"
file = "/usr/lib/libcmumps.a"

[[file]]
name = "libdmumps_a"
file = "/usr/lib/libdmumps.a"

[[file]]
name = "libsmumps_a"
file = "/usr/lib/libsmumps.a"

[[file]]
name = "libzmumps_a"
file = "/usr/lib/libzmumps.a"
