maintainers:
- github: lilydjwg
build_prefix: archlinuxcn-x86_64
update_on:
- source: alpm
  strip_release: true
  alpm: sysdig
- source: cmd
  cmd: LANG=C pacman --dbpath ~/.lilac/pacmandb -Si linux-lily | awk '$1 == "Version"
    { print $3 }'
- alias: protobuf
- alias: jsoncpp
- source: alpm
  alpm: grpc
  provided: libgrpc++_unsecure.so
- alias: libssl
- source: archfiles
  pkgpart: extra/x86_64/re2
  filename: 'libre2.so.\d+'
