[[library]]
name = "libxcb"

[[library]]
name = "libxcb_composite"
file = "libxcb-composite"

[[library]]
name = "libxcb_damage"
file = "libxcb-damage"

[[library]]
name = "libxcb_dpms"
file = "libxcb-dpms"

[[library]]
name = "libxcb_dri2"
file = "libxcb-dri2"

[[library]]
name = "libxcb_dri3"
file = "libxcb-dri3"

[[library]]
name = "libxcb_glx"
file = "libxcb-glx"

[[library]]
name = "libxcb_present"
file = "libxcb-present"

[[library]]
name = "libxcb_randr"
file = "libxcb-randr"

[[library]]
name = "libxcb_record"
file = "libxcb-record"

[[library]]
name = "libxcb_render"
file = "libxcb-render"

[[library]]
name = "libxcb_res"
file = "libxcb-res"

[[library]]
name = "libxcb_screensaver"
file = "libxcb-screensaver"

[[library]]
name = "libxcb_shape"
file = "libxcb-shape"

[[library]]
name = "libxcb_shm"
file = "libxcb-shm"

[[library]]
name = "libxcb_sync"
file = "libxcb-sync"

[[library]]
name = "libxcb_xf86dri"
file = "libxcb-xf86dri"

[[library]]
name = "libxcb_xfixes"
file = "libxcb-xfixes"

[[library]]
name = "libxcb_xinerama"
file = "libxcb-xinerama"

[[library]]
name = "libxcb_xinput"
file = "libxcb-xinput"

[[library]]
name = "libxcb_xkb"
file = "libxcb-xkb"

[[library]]
name = "libxcb_xtest"
file = "libxcb-xtest"

[[library]]
name = "libxcb_xv"
file = "libxcb-xv"

[[library]]
name = "libxcb_xvmc"
file = "libxcb-xvmc"
