[[binary]]
name = "fc_cache"
file = "fc-cache"

[[binary]]
name = "fc_cat"
file = "fc-cat"

[[binary]]
name = "fc_conflist"
file = "fc-conflist"

[[binary]]
name = "fc_list"
file = "fc-list"

[[binary]]
name = "fc_match"
file = "fc-match"

[[binary]]
name = "fc_pattern"
file = "fc-pattern"

[[binary]]
name = "fc_query"
file = "fc-query"

[[binary]]
name = "fc_scan"
file = "fc-scan"

[[binary]]
name = "fc_validate"
file = "fc-validate"

[[library]]
name = "libfontconfig"

# TODO?
# JLLWrappers.@declare_file_product(fonts_conf)
