[[library]]
name = "libwayland_client"
file = "libwayland-client"

[[library]]
name = "libwayland_cursor"
file = "libwayland-cursor"

[[library]]
name = "libwayland_egl"
file = "libwayland-egl"

[[library]]
name = "libwayland_server"
file = "libwayland-server"

[[binary]]
name = "wayland_scanner"
file = "wayland-scanner"
